source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '8.0'
use_frameworks!

pod 'SDWebImage'
pod 'Alamofire' 
pod 'MagicalRecord'
pod 'MBProgressHUD'
pod 'NYXImagesKit'
pod 'UIImage+Additions'
pod 'MJRefresh'
pod 'ActionSheetPicker-3.0'
pod 'IDMPhotoBrowser'
pod 'RDVTabBarController'
pod 'SSKeychain'
pod 'UIImage+BlurredFrame'
pod 'UIAlertController+Blocks'
pod 'IQKeyboardManager'
pod 'SWXMLHash', '~> 2.3.0'
pod 'Kanna'
pod 'JSQWebViewController'
